version: "3.9"

services:
  db:
    image: postgres:16rc1-alpine3.18
    ports:
      - "5431:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: uvicorn generator.asgi:application --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/code
      - ./temp/:/tmp/
    ports:
      - "80:80"
    depends_on:
      - db
    # env_file:
    #   - ".env.local"
