version: "3.9"

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  web:
    build: .
    command: uvicorn generator.asgi:application --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/code
      - ./temp/:/tmp/
      - ./requirements.txt:/code/requirements.txt
    ports:
      - "80:80"
    depends_on:
      - db
  #   # env_file:
  #   #   - ".env.local"
